on:
  push:
    # Respond to a push event on every brannch other than Github Pages.
    branches:
      - '!gh-pages'
      - '*'

  pull_request:
    branches:
      - '!gh-pages'

  # Scheduled build so pipeline failures are noticed quicker.
  schedule:
    - cron: '30 12 * * *'

name: Update Flags
jobs:
  update:
    name: Update Flags
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/setup-node@master
    - name: Fetch Dependencies
      run: cd src ; npm install
    - name: "Test & Deploy Flags"
      uses: "./src/"
      with:
        feature-flags-github-app-id: ${{ secrets.FEATURE_FLAGS_APP_ID }}
        feature-flags-private-key: ${{ secrets.FEATURE_FLAGS_PRIVATE_KEY }}